url: https://playfulexperiences.github.io
baseurl: /2018DegreeShowWeb

# Site settings
title: Playful Experiences
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Jade Hall-Smith
  pic: "jade"
  social:
    - title: twitter
      url: https://twitter.com/VariegatedGames
    - title: linkedin
      url: https://www.linkedin.com/in/jade-hall-smith
    - title: globe
      url: https://variegated-games.com

- name: Matthew Deline
  pic: "matt"
  social:
    - title: twitter
      url: https://twitter.com/mattdeline
    - title: github
      url: https://github.com/aradicaldreamer
    - title: youtube
      url: https://youtube.com/matthewdeline
    - title: linkedin
      url: https://linkedin.com/in/matthewdeline
    - title: globe
      url: https://www.matthewdeline.com

- name: Alex Fletcher
  pic: "alex"
  social: []

- name: Benjamin Tandy
  pic: "placeholder"
  social:
    - title: twitter
      url: https://twitter.com/frndcldben
    - title: globe
      url: https://www.afriendcalledben.com

- name: Billy Karnchanapee
  pic: "billy"
  social:
    - title: twitter
      url: https://twitter.com/foxcircles
    - title: globe
      url: https://mitunayon.github.io/

- name: Doruk Hasdogan
  pic: "doruk"
  social:
    - title: twitter
      url: https://twitter.com/DorukHasdogan
    - title: behance
      url: https://www.behance.net/Malebolge
    - title: linkedin
      url: https://www.linkedin.com/in/dhasd
    - title: youtube
      url: https://www.youtube.com/channel/UCfGO0ZESaALif0Y12DF21kQ

- name: Ece Hasdogan
  pic: "ece"
  social:
    - title: twitter
      url: https://twitter.com/EceSeyrek
    - title: linkedin
      url: https://www.linkedin.com/in/ecesey
    - title: youtube
      url: https://www.youtube.com/channel/UCNsUSUUsKNzML6Vn3TCT4yw
    - title: instagram
      url: https://www.instagram.com/scarce.queen
    - title: behance
      url: https://www.behance.net/ScarceQueen
    - title: globe
      url: https://artstation.com/eceseyrekhasdogan

- name: Julia Makivic
  pic: "placeholder"
  social: []

- name: Phoenix Perry
  pic: "placeholder"
  social: []

- name: Raymond Vermeulen
  pic: "placeholder"
  social:
    - title: twitter
      url: https://twitter.com/raymondvrmln
    - title: globe
      url: http://rvermeulen.com

- name: Tommy Graven
  pic: "tommy"
  social:
    - title: globe
      url: https://www.tommygraven.com
    - title: twitter
      url: https://twitter.com/tommy_goodgame

- name: Hugh Kennedy
  pic: "hughsk"
  social:
    - title: twitter
      url: https://twitter.com/hughskennedy
    - title: globe
      url: https://hughsk.io/
    - title: github
      url: https://github.com/hughsk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
